version: '3.8'

services:
  telegram_bot_support:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - .:/usr/src/app
    restart: always